version: '3'
services:
    web:
        image: nginx:alpine
        container_name: mi2rdf-web
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
            - "./web:/var/www/html"
        restart: always
        labels:
            - "traefik.docker.network=traefik"
            - "traefik.frontend.rule=Host:demo.netwerkdigitaalerfgoed.nl;PathPrefix:/mi2rdf;PathPrefixStrip:/mi2rdf"
            - "traefik.port=80"
#       networks:
#           - traefik
        ports:
            - "80:80"
        depends_on:
            - php
            - database

    php:
        build: php-fpm
        container_name: mi2rdf-php-fpm
        volumes:
            - "./etc/php/php.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini:ro"
            - "./web:/var/www/html:ro"
            - filestorevolume:/filestore
#       networks:
#           - traefik

    queue:
        image:  rabbitmq:management-alpine
        container_name: mi2rdf-queue
        volumes:
            - "queuevolume:/var/lib/rabbitmq/mnesia/"
            - "./queue/config/definitions.json:/opt/definitions.json:ro"
            - "./queue/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            - RABBITMQ_ERLANG_COOKIE='en_dee_eee'
#       networks:
#           - traefik

    consumer:
        build: consumer
        container_name: mi2rdf-consumer
        volumes:
            - filestorevolume:/filestore
        environment:
            - TRIPLY_TOKEN=${TRIPLY_TOKEN}
            - TRIPLY_USER=${TRIPLY_USER}
            - TRIPLY_DATASET=${TRIPLY_DATASET}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        depends_on:
            - "queue"
            - "database"
#       networks:
#           - traefik

    composer:
        image: "composer"
        container_name: mi2rdf-composer
        volumes:
            - "./web:/app"
        command: install --ignore-platform-reqs

    database:
        image: mariadb:10.4
        container_name: mi2rdf-database
        volumes:
            - "./database/config:/docker-entrypoint-initdb.d/:ro"
            - "datavolume:/var/lib/mysql"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_INITDB_SKIP_TZINFO=1
        ports:
            - "3306:3306"
#       networks:
#           - traefik

#networks:
#   traefik:
#       external: true

volumes:
    filestorevolume:
    queuevolume:
    datavolume: